stages:
  #- test
  - deploy

variables:
  APP_NAME:
    description: "The name of the app. The pipeline will push to APP_NAME and APP_NAME-staging"
  LIVE_URL:
    description: "URL of the live/production app"
  STAGING_URL:
    description: "URL of the staging app"
  LIVE_SERVER:
    description: "Dokku server to push the live app to"
  STAGING_SERVER:
    description: "Dokku server to push the staging app to"
  LIVE_BRANCH:
    value: "live"
    description: "Branch to deploy to live environment"
  STAGING_BRANCH:
    value: "staging"
    description: "Branch to deploy to staging environment"


deploy_live:
  image: ilyasemenov/gitlab-ci-git-push
  stage: deploy
  environment:
    name: production
    url: $LIVE_URL
  script:
    - "git-push ssh://dokku@$LIVE_SERVER:22/$APP_NAME"
  rules:
    - if: $CI_COMMIT_REF_NAME == $LIVE_BRANCH && $APP_NAME != "" && $LIVE_URL != "" && $LIVE_SERVER != ""

deploy_staging:
  image: ilyasemenov/gitlab-ci-git-push
  stage: deploy
  environment:
    name: staging
    url: $STAGING_URL
  script:
    - "git-push ssh://dokku@$STAGING_SERVER:22/$APP_NAME-staging"
  rules:
    - if: $CI_COMMIT_REF_NAME == $STAGING_BRANCH && $APP_NAME != "" && $STAGING_URL != "" && $STAGING_SERVER != ""

